name: Docker CI
on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  NEXUS_URL: 20.235.80.53:8082

jobs:
  build:
    name: Docker Build CI
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Login
        # You may pin to the exact commit or the version.
        # uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2
        uses: docker/login-action@v4.0.0
        with:
          # Server address of Docker registry. If not set then will default to Docker Hub
          registry: $NEXUS_URL
          # Username used to log against the Docker registry
          username: ${{ secrets.NEXUS_USERNAME }}
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.NEXUS_PASSWORD }}
      
      - name: Build and push Docker images
        uses: docker/build-push-action@v7.0.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: $NEXUS_URL/react-app:${{ github.run_number }}
      


                
