name: Docker CI
on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  NEXUS_URL: http://20.235.80.53:8082

jobs:
  build:
    name: Docker Build CI
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Allow HTTP Registry
        run: |
          echo '{"insecure-registries": ["20.235.80.53:8082"]}' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker

      - name: Docker Build
        run: docker build -t react-app:${{ github.run_number }} .

      - name: Docker Login
        run: echo "${{ secrets.NEXUS_PASSWORD }}" | docker login $NEXUS_URL -u ${{ secrets.NEXUS_USERNAME }} --password-stdin

      - name: Docker Tag
        run: docker tag react-app:${{ github.run_number }} $NEXUS_URL/react-app:${{ github.run_number }}

      - name: Docker Push
        run: docker push $NEXUS_URL/react-app:${{ github.run_number }}
