name: Docker CI
on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  NEXUS_URL: acrforall.azurecr.io


jobs:
  scan-superlinter:
    runs-on: ubuntu-latest

    permissions:
      # contents permission to clone the repository
      contents: read
      packages: read
      # issues and pull-requests permissions to write results as pull
      # request comments. Omit them if you don't need summary comments
      issues: write
      pull-requests: write
      # To report GitHub Actions status checks. Omit if you don't need
      # to update commit status
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Super-linter
        uses: super-linter/super-linter@v8.5.0 # x-release-please-version
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_DOCKERFILE_HADOLINT: true

  scan-trivy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Build an image from Dockerfile
        run: docker build -t ${{ env.NEXUS_URL }}/my-app:${{ github.run_number }} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: '${{ env.NEXUS_URL }}/my-app:${{ github.run_number }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      
  # build:
  #   name: Docker Build CI
  #   runs-on: self-hosted
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
    
  #     # - name: Configure insecure registry
  #     #   run: |
  #     #     sudo mkdir -p /etc/docker
  #     #     echo '{"insecure-registries": ["20.235.80.53:8082"]}' | sudo tee /etc/docker/daemon.json
  #     #     sudo systemctl restart docker
  #     #     sleep 5
    
  #     - name: Docker Login
  #       uses: docker/login-action@v4.0.0
  #       with:
  #         registry: ${{ env.NEXUS_URL }}
  #         username: ${{ secrets.ACR_USER }}
  #         password: ${{ secrets.ACR_PASS }}
      
  #     - name: Build and push Docker images
  #       uses: docker/build-push-action@v7.0.0
  #       with:
  #         context: .
  #         file: ./Dockerfile
  #         push: true
  #         tags: ${{ env.NEXUS_URL }}/react-app:${{ github.run_number }}

      


                
